/*

	TVP2 ( T Visual Presenter 2 )  A script authoring tool
	Copyright (C) 2000-2009 W.Dee <dee@kikyou.info> and contributors

	See details of license at "license.txt"
*/
/* This file is always generated by makestub.pl . */
/* Modification by hand will be lost. */


#include "tjsCommHead.h"
// 自動生成されるので空でよい
// 生成されるのは公開関数名とその関数ポインタ。
// プラグインで利用される。
void TVPExportFunctions()
{
}

