/**
 * 擬似コードによるマニュアル
 */

class Layer {

    /**
     * 明度とコントラスト
     * @param brightness 明度 -255 ～ 255, 負数の場合は暗くなる
     * @param contrast コントラスト -100 ～100, 0 の場合変化しない
     */
    function light(brightness, contrast);

    /**
	 * 色相と彩度
	 * @param hue 色相
	 * @param sat 彩度
	 * @param blend ブレンド 0 (効果なし) ～ 1 (full effect)
	 */
	function colorize(hue, sat, blend);

	/**
	 * 色相と彩度と輝度の変更
	 * @param hue 色相 -180～180 (度)
	 * @param saturation 彩度 -100～100 (%)
	 * @param luminance 輝度 -100～100 (%)
	 */
	function modulate(hue, saturation, luminance);
	
    /**
	 * ノイズ追加
	 * @param level ノイズレベル 0 (no noise) ～ 255 (lot of noise).
	 */
    function noise(level);

	/**
	 * ノイズ生成（元の画像を無視してグレースケールのホワイトノイズを描画／α情報は維持）
	 */
    function generateWhiteNoise();

	/**
	 * ガウスぼかし処理
	 * @param radius ぼかし度合い
	 */
	void gaussianBlur(float radius);
};
