#include "tjsCommHead.h"
const tjs_char* MESSAGE_RESOURCE[] = {
	TJS_W("内部エラーが発生しました"),
	TJS_W("警告: "),
	TJS_W("グローバルでない場所で後置 ! 演算子が使われています(この演算子の挙動はTJS2 version 2.4.1 で変わりましたのでご注意ください)"),
	TJS_W("文字列を UNICODE 文字列に変換できません。解釈できない文字が含まれてます。正しいデータが指定されているかを確認してください。データが破損している可能性もあります"),
	TJS_W("%1 から %2 へ型を変換できません"),
	TJS_W("%1 から Object へ型を変換できません。Object 型が要求される文脈で Object 型以外の値が渡されるとこのエラーが発生します"),
	TJS_W("識別子を指定してください"),
	TJS_W("論理値が求められている場所で = 演算子が使用されています(== 演算子の間違いですか？代入した上でゼロと値を比較したい場合は、(A=B) != 0 の形式を使うことをお勧めします)"),
	TJS_W("不正な代入か不正な式の操作です"),
	TJS_W("メモリが足りません"),
	TJS_W("この式からは値を得ることができません"),
	TJS_W("null オブジェクトにアクセスしようとしました"),
	TJS_W("メンバ ""%1"" が見つかりません"),
	TJS_W("メンバが見つかりません"),
	TJS_W("呼び出そうとした機能は未実装です"),
	TJS_W("不正な引数です"),
	TJS_W("引数の数が不正です"),
	TJS_W("関数ではないかプロパティの種類が違います"),
	TJS_W("Dictionary または Array クラスのオブジェクトを指定してください"),
	TJS_W("Array クラスのオブジェクトを指定してください"),
	TJS_W("文字列メモリブロックを解放できません"),
	TJS_W("文字列メモリブロックを確保できません"),
	TJS_W("""break"" または ""continue"" はここに書くことはできません"),
	TJS_W("""case"" はここに書くことはできません"),
	TJS_W("""return"" はここに書くことはできません"),
	TJS_W("文字列定数/正規表現/オクテット即値が終わらないままスクリプトの終端に達しました"),
	TJS_W("数値として解釈できません"),
	TJS_W("コメントが終わらないままスクリプトの終端に達しました"),
	TJS_W("不正な文字です : '%1'"),
	TJS_W("%1 がありません"),
	TJS_W("文法エラーです(%1)"),
	TJS_W("条件コンパイル式にエラーがあります"),
	TJS_W("スーパークラスが存在しないかスーパークラスを特定できません"),
	TJS_W("不正な VM コードです"),
	TJS_W("値が範囲外です"),
	TJS_W("読み込み専用あるいは書き込み専用プロパティに対して行えない操作をしようとしました"),
	TJS_W("実行コンテキストが違います"),
	TJS_W("オブジェクトはすでに無効化されています"),
	TJS_W("""..."" は関数外では使えません"),
	TJS_W("不正な日付文字列の形式です"),
	TJS_W("不正な日付・時刻です"),
	TJS_W("""Exception"" が存在しないため例外オブジェクトを作成できません"),
	TJS_W("不正な書式文字列です"),
	TJS_W("0 で除算をしようとしました"),
	TJS_W("乱数系列を初期化できません(おそらく不正なデータが渡されました)"),
	TJS_W("識別子"),
	TJS_W("[TJSスクリプト管理外]"),
	TJS_W("合計 %1 個のオブジェクトが解放されていません"),
	TJS_W("\r\n                     "),
	TJS_W("\n                     "),
	TJS_W("オブジェクト %1 [%2] が解放されていません。オブジェクト作成時の呼び出し履歴は以下の通りです:\r\n                     %3"),
	TJS_W("オブジェクト %1 [%2] が解放されていません。オブジェクト作成時の呼び出し履歴は以下の通りです:\n                     %3"),
	TJS_W("オブジェクトのタイプとオブジェクト作成時の履歴による分類"),
	TJS_W("オブジェクトのタイプによる分類"),
	TJS_W("%1 個 : [%2]\r\n                     %3"),
	TJS_W("%1 個 : [%2]\n                     %3"),
	TJS_W("%1 個 : [%2]"),
	TJS_W("%4: 削除中のオブジェクト %1[%2] 上でコードが実行されています。このオブジェクトの作成時の呼び出し履歴は以下の通りです:\r\n                     %3"),
	TJS_W("%4: 削除中のオブジェクト %1[%2] 上でコードが実行されています。このオブジェクトの作成時の呼び出し履歴は以下の通りです:\n                     %3"),
	TJS_W("書き込みエラーが発生しました"),
	TJS_W("読み込みエラーが発生しました。ファイルが破損している可能性や、デバイスからの読み込みに失敗した可能性があります"),
	TJS_W("シークエラーが発生しました。ファイルが破損している可能性や、デバイスからの読み込みに失敗した可能性があります"),
	TJS_W("バイトコードファイル読み込みエラー。ファイルが壊れているかバイトコードとは異なるファイルです"),
	TJS_W("Object Hash Map ログのバージョンが一致しません"),
	TJS_W("不正な Object Hash Map ログ"),
	TJS_W("未知のエラー %08X"),
	TJS_W("不明な pack/unpack TEMPLATE 文字です"),
	TJS_W("不明な bit string 文字です"),
	TJS_W("不明な16進数文字です"),
	TJS_W("uuencode はサポートしていません"),
	TJS_W("BER圧縮はサポートしていません"),
	TJS_W("'p' unpack はサポートしていません"),
	TJS_W("'P' unpack はサポートしていません"),
	TJS_W("吉里吉里[きりきり] Z 実行コア/%1 (Compiled on %DATE% %TIME%) TJS2/%2 Copyright (C) 1997-2013 W.Dee and contributors All rights reserved."),
	TJS_W("バージョン情報の詳細は -about を付けて起動すると閲覧できます"),
	TJS_W("http://krkrz.github.io/"),
	TJS_W("内部エラーが発生しました: at %1 line %2"),
	TJS_W("不正なパラメータです"),
	TJS_W("-debug オプションが指定されているため,現在 吉里吉里はデバッグモードで動作しています。デバッグモードでは十分な実行速度が出ない場合があるので注意してください"),
	TJS_W("コマンドラインパラメータ %1 に指定された値 %2 は無効のためデフォルトの設定を用います"),
	TJS_W("コマンドラインパラメータ %1 に指定された値 %2 は無効です"),
	TJS_W("未実装の機能を呼び出そうとしました"),
	TJS_W("ストレージ %1 を開くことができません"),
	TJS_W("ストレージ %1 が見つかりません"),
	TJS_W("ストレージ %1 を書き込み用に開くことができません。ファイルが書き込み禁止になっていないか、あるいはファイルに書き込み権限があるかどうか、あるいはそもそもそれが書き込み可能なメディアやファイルなのかを確認してください"),
	TJS_W("ストレージ %1 がアーカイブ %2 の中に見つかりません"),
	TJS_W("パス名 %1 は無効な形式です。形式が正しいかどうかを確認してください"),
	TJS_W("""%1"" は対応していないメディアタイプです"),
	TJS_W("%1 は実行可能ファイルに見えますが、これに結合されたアーカイブを発見できませんでした"),
	TJS_W("%1 は XP3 アーカイブではないか、対応できない形式です。アーカイブファイルを指定すべき場面で通常のファイルを指定した場合、あるいは対応できないアーカイブファイルを指定した場合などにこのエラーが発生しますので、確認してください"),
	TJS_W("パス名の最後には '>' または '/' を指定してください (吉里吉里２ 2.19 beta 14 よりアーカイブの区切り記号が '#' から '>' に変わりました)"),
	TJS_W("(注意) '#' がファイル名 ""%1"" に含まれています。アーカイブの区切り文字は吉里吉里２ 2.19 beta 14 より'#' から '>' に変わりました。もしアーカイブの区切り文字のつもりで '#' を使用した場合は、お手数ですが '>' に変えてください"),
	TJS_W("ストレージ名 %1 をローカルファイル名に変換できません。アーカイブファイル内のファイルや、ローカルファイルでないファイルはローカルファイル名に変換できません。"),
	TJS_W("読み込みエラーです。ファイルが破損している可能性や、デバイスからの読み込みに失敗した可能性があります"),
	TJS_W("書き込みエラーです"),
	TJS_W("シークに失敗しました。ファイルが破損している可能性や、デバイスからの読み込みに失敗した可能性があります"),
	TJS_W("ファイルの長さを切り詰めるのに失敗しました"),
	TJS_W("メモリ確保に失敗しました。"),
	TJS_W("ファイルの展開に失敗しました。未対応の圧縮形式が指定されたか、あるいはファイルが破損している可能性があります"),
	TJS_W("ファイルの圧縮に失敗しました"),
	TJS_W("アーカイブにデータを書き込むことはできません"),
	TJS_W("%1 は未対応の暗号化形式か、データが破損しています"),
	TJS_W("%1 は未対応のエンコード方式です。"),
	TJS_W("認識できないモード文字列の指定です(%1)"),
	TJS_W("%1 は未知の画像形式です"),
	TJS_W("%1 について適切な拡張子を持ったファイルを見つけられませんでした"),
	TJS_W("マスク画像のサイズがメイン画像のサイズと違います"),
	TJS_W("領域画像 %1 はメイン画像とサイズが違います"),
	TJS_W("画像読み込み中にエラーが発生しました/%1"),
	TJS_W("JPEG 読み込み中にエラーが発生しました/%1"),
	TJS_W("PNG 読み込み中にエラーが発生しました/%1"),
	TJS_W("ERI 読み込み中にエラーが発生しました/%1"),
	TJS_W("TLG 読み込み中にエラーが発生しました/%1"),
	TJS_W("無効な保存画像形式です(%1)"),
	TJS_W("8bpp 画像に対しては行えない操作を行おうとしました"),
	TJS_W("32bpp 画像に対しては行えない操作を行おうとしました"),
	TJS_W("Window クラスのオブジェクトを指定してください"),
	TJS_W("Layer クラスのオブジェクトを指定してください"),
	TJS_W("Layer クラスか Bitmap クラスのオブジェクトを指定してください"),
	TJS_W("この操作で mode に omAuto を指定することは出来ません"),
	TJS_W("画像サイズの横幅あるいは縦幅を 0 以下の数に設定することはできません"),
	TJS_W("プライマリレイヤは不可視にできません"),
	TJS_W("プライマリレイヤは移動できません"),
	TJS_W("自分自身を親とすることはできません"),
	TJS_W("自分自身の前後や親の異なるレイヤの前後に移動することはできません"),
	TJS_W("プライマリレイヤや兄弟の無いレイヤは前後に移動することはできません"),
	TJS_W("別のプライマリレイヤ下にレイヤを移動することはできません"),
	TJS_W("レイヤ領域に画像の無い領域が発生しました"),
	TJS_W("すでにモーダルなレイヤの親レイヤ、あるいは不可視/無効なレイヤをモーダルにすることはできません"),
	TJS_W("この type のレイヤでは描画や画像読み込みや画像サイズ/位置の変更/取得はできません"),
	TJS_W("転送元レイヤは画像を持っていません"),
	TJS_W("%1 はこの type のレイヤでは使用できません"),
	TJS_W("%1 ではこの face に描画できません"),
	TJS_W("指定されたレイヤタイプ変換はできません"),
	TJS_W("負の不透明度はこの face では指定できません"),
	TJS_W("転送元がビットマップ外の領域を含んでいます。正しい範囲に収まるように転送元を指定してください"),
	TJS_W("矩形ブラーの範囲は必ず(0,0)をその中に含む必要があります。leftとrightが両方とも正の数値、あるいは両方とも負の数値という指定はできません(topとbottomに対しても同様)"),
	TJS_W("矩形ブラーの範囲が大きすぎます。矩形ブラーの範囲は1677万以下である必要があります"),
	TJS_W("フォーカス変更処理中はフォーカスを新たに変更することはできません"),
	TJS_W("ウィンドウにレイヤがありません"),
	TJS_W("ウィンドウにはすでにプライマリレイヤがあります"),
	TJS_W("イベント %1 にはパラメータが必要です"),
	TJS_W("イベント %1 にはパラメータ %2 が必要です"),
	TJS_W("イベント名 %1 は未知のイベント名です"),
	TJS_W("矩形外を指定されました"),
	TJS_W("画面更新中はこの機能を実行できません"),
	TJS_W("このクラスはインスタンスを作成できません"),
	TJS_W("%1 は対応できない Wave 形式です"),
	TJS_W("現在のトランジションを停止させてから新しいトランジションを開始してください。同じレイヤに対して複数のトランジションを同時に実行しようとするとこのエラーが発生します"),
	TJS_W("トランジションハンドラでエラーが発生しました : %1"),
	TJS_W("トランジション %1 は既に登録されています"),
	TJS_W("トランジションハンドラ %1 が見つかりません"),
	TJS_W("トランジション元を指定してください"),
	TJS_W("このレイヤは画像を持つことはできません"),
	TJS_W("トランジション元とトランジション先はともに画像を持っている必要があります"),
	TJS_W("ルール画像 %1 を読み込むことができません"),
	TJS_W("オプション %1 を指定してください"),
	TJS_W("トランジション元(%1)とトランジション先(%2)のレイヤのサイズが一致しません"),
	TJS_W("トランジション元のトランジション元が自分自身です"),
	TJS_W("警告 : メソッド %1 の %2 番目に渡された hda パラメータは、吉里吉里２ 2.23 beta 2 より無視されるようになりました。代わりに Layer.holdAlpha プロパティを用いてください。"),
	TJS_W("複数の WaveSoundBuffer を一つのフィルタで同時に使用することはできません"),
	TJS_W("window は 64～32768 の範囲の 2 の累乗で無ければなりません"),
	TJS_W("overlap は 2～32 の範囲の 2 の累乗で無ければなりません"),
	TJS_W("Bitmap を非同期読込み中のため、このメソッドは呼び出せません"),
	TJS_W("クリップボードへのコピーに失敗しました"),
	TJS_W("UTF-16では発生し得ないUTF-8への変換です"),
	TJS_W("(info) 起動スクリプト読込み中 : "),
	TJS_W("(info) 起動スクリプト実行終了。"),
	TJS_W("sizeof(tjs_char) は 2 か 4 でなければなりません。"),
	TJS_W("メディア名 ""%1"" は既に登録されています"),
	TJS_W("メディア名 ""%1"" は登録されていません"),
	TJS_W("(info) 自動検索パステーブルを再構築しています ..."),
	TJS_W("(info) Total %1 file(s) found, %2 file(s) activated. (%3ms)"),
	TJS_W("Error in retrieving System.onActivate/onDeactivate : %1"),
	TJS_W("The host is not a 16-bit unicode system."),
	TJS_W("(info) Trying to read XP3 virtual file system information from : %1"),
	TJS_W("Specified storage had been protected!"),
	TJS_W("(info) 失敗。"),
	TJS_W("(info) Done. (contains %1 file(s), %2 segment(s))"),
	TJS_W("\r\n\r\n\r\n==============================================================================\r\n==============================================================================\r\n"),
	TJS_W("\n\n\n==============================================================================\n==============================================================================\n"),
	TJS_W("ＭＳ Ｐゴシック"),
	TJS_W("Can't open font file '%1$s'"),
	TJS_W("フォント '%1$s' は使用できません"),
	TJS_W("フォント ラスタライズ エラー."),
	TJS_W("BITFIELDS not supported."),
	TJS_W("Compressed BMP not supported."),
	TJS_W("Unsupported color mode for palettized image."),
	TJS_W("This is not a Windows BMP file or an OS/2 BMP file."),
	TJS_W("Non-supported header version."),
	TJS_W("(info) Touching "),
	TJS_W(" ... 中断 [タイムアウト]"),
	TJS_W(" ... 中断 [バイトサイズ上限値超過]"),
	TJS_W("Faild glyph for DrawGlyph."),
	TJS_W("Panic! Layer object is not properly constructed. The constructor was not called??"),
	TJS_W("不明な update タイプ"),
	TJS_W("不明な transition タイプ"),
	TJS_W("Update タイプの tutGiveUpdate はサポートしていません"),
	TJS_W("エラーコード : "),
	TJS_W("JPEG はパレット画像をサポートしていません"),
	TJS_W("libpng エラー."),
	TJS_W("Unsupported color type for palattized image"),
	TJS_W("サポートしていないカラータイプ"),
	TJS_W("Too large image"),
	TJS_W("PNG save error."),
	TJS_W("TLG cannot be used as universal transition rule, province(_p) or mask(_m) images."),
	TJS_W("Unsupported color count : "),
	TJS_W("Data flag must be 0 (any flags are not yet supported)"),
	TJS_W("サポートしていないカラータイプです : "),
	TJS_W("外部 golomb ビット長テーブルはサポートしていません"),
	TJS_W("サポートしていないエントロピーコードメソッドです"),
	TJS_W("不正な TLG ヘッダーか、サポートしていない TLG バージョンです"),
	TJS_W("Malformed TLG SDS tag structure, missing colon after name length"),
	TJS_W("Malformed TLG SDS tag structure, missing equals after name"),
	TJS_W("Malformed TLG SDS tag structure, missing colon after value length"),
	TJS_W("Malformed TLG SDS tag structure, missing comma after a tag"),
	TJS_W("ファイルサイズがゼロです"),
	TJS_W("メモリ確保に失敗しました"),
	TJS_W("ファイル読込みエラー"),
	TJS_W("シグネチャが見つからないか、プリレンダーフォントファイルではありません"),
	TJS_W("16 ビット UNICODE フォントファイルではありません"),
	TJS_W("不正なバージョンのヘッダーです"),
	TJS_W("SaveTLG6: メモリ不足です"),
	TJS_W("SaveTLG6: ビット長が長すぎます (渡された画像が大きすぎる可能性があります)"),
	TJS_W("渡された Draw Device からインターフェイスを取得できません"),
	TJS_W("スクリプトで例外が発生しました"),
	TJS_W("ハードウェア例外が発生しました"),
	TJS_W("スクリプトエディタ (メイン)"),
	TJS_W("スクリプトエディタ (例外通知)"),
	TJS_W("フォルダ/アーカイブの選択画面を表示しようとしましたが krdevui.dll が見つからないので表示できません.\n実行するフォルダ/アーカイブはコマンドラインの引数として指定してください"),
	TJS_W("krdevui.dll が異常か、バージョンが一致しません"),
	TJS_W("無効な色深度です"),
	TJS_W("プラグイン %1 を読み込めません"),
	TJS_W("%1 は有効なプラグインではありません"),
	TJS_W("プラグインの解放に失敗しました"),
	TJS_W("プラグインの接続中に他のプラグインを接続することはできまません"),
	TJS_W("異常な Susie プラグインです"),
	TJS_W("Susie プラグインでエラーが発生しました/エラーコード %1"),
	TJS_W("指定されたプラグインは使用中のため解放できません"),
	TJS_W("%1 は読み込まれていません"),
	TJS_W("ビットマップ用メモリを確保できません/%1(size=%2)"),
	TJS_W("スキャンライン %1 は範囲(0～%2)を超えています"),
	TJS_W("プラグインでエラーが発生しました/%1"),
	TJS_W("指定されたドライブでは CD-DA を再生できません"),
	TJS_W("CD-DA を再生できるドライブが見つかりません"),
	TJS_W("MCI でエラーが発生しました : %1"),
	TJS_W("有効な SMF ファイルではありません : %1"),
	TJS_W("指定されたメッセージは MIDI メッセージとして有効な形式ではありません"),
	TJS_W("DirectSound を初期化できません : %1"),
	TJS_W("DirectSound セカンダリバッファを作成できません : %1/%2"),
	TJS_W("ループ情報 %1 は異常です"),
	TJS_W("指定されたメニュー項目はこのメニュー項目の子ではありません"),
	TJS_W("Direct3D を初期化できません : %1"),
	TJS_W("適合する画面モードが見つかりません : %1"),
	TJS_W("フルスクリーンに切り替えられません : %1"),
	TJS_W("フルスクリーン中では操作できないプロパティを設定しようとしました"),
	TJS_W("フルスクリーン中では操作できないメソッドを呼び出そうとしました"),
	TJS_W("マウスカーソル %1 の読み込みに失敗しました"),
	TJS_W("ビデオ/Shockwave Flash を再生するためには krmovie.dll / krflash.dll が必要ですが 読み込むことができません"),
	TJS_W("krmovie.dll/krflash.dll が異常か 対応できないバージョンです"),
	TJS_W("krmovie.dll/krflash.dll 内でエラーが発生しました/%1"),
	TJS_W("ウィンドウはすでに存在していません"),
	TJS_W("レンダリング済みフォントのマッピングに失敗しました : %1"),
	TJS_W("%1 に書き込みできません。ソフトウェアが実行中のままになっていないか、あるいは書き込み権限があるかどうかを確認してください"),
	TJS_W("%1 の終了を確認できないため、これを削除できませんでした(このファイルは削除して結構です)"),
	TJS_W("%1 を実行できません"),
	TJS_W("プラグインから関数 %1 を要求されましたが、その関数は本体内に存在しません。プラグインと本体のバージョンが正しく対応しているか確認してください"),
	TJS_W(" = (例外発生)"),
	TJS_W("コンソール : "),
	TJS_W("(info) Listing files in %1 …"),
	TJS_W("(info) Total physical memory : %1"),
	TJS_W("(info) Selected project directory : %1"),
	TJS_W("too small executable size."),
	TJS_W("(info) Loading executable embedded options failed (ignoring) : %1"),
	TJS_W("(info) Loading executable embedded options succeeded."),
	TJS_W("file not found."),
	TJS_W("(info) Loading configuration file ""%1"" failed (ignoring) : %2"),
	TJS_W("(info) Loading configuration file ""%1"" succeeded."),
	TJS_W("(info) Data path does not exist, trying to make it ... %1"),
	TJS_W("成功。"),
	TJS_W("失敗。"),
	TJS_W("(info) Data path : %1"),
	TJS_W("(info) Specified option(s) (earlier item has more priority) :"),
	TJS_W(" (none)"),
	TJS_W("(info) CPU clock (roughly) : %dMHz"),
	TJS_W("%1 (%2) 上で実行が開始されました"),
	TJS_W("吉里吉里"),
	TJS_W("不明なエラーが発生しました。"),
	TJS_W("終了コード: %d\n"),
	TJS_W("致命的なエラーが発生しました"),
	TJS_W("有効なデジタイザー"),
	TJS_W("統合型のタッチ デジタイザーが入力に使用されています。"),
	TJS_W("外付けのタッチ デジタイザーが入力に使用されています。"),
	TJS_W("統合型のペン デジタイザーが入力に使用されています。"),
	TJS_W("外付けのペン デジタイザーが入力に使用されています。"),
	TJS_W("複数入力がサポートされた入力デジタイザーが入力に使用されています。"),
	TJS_W("入力デジタイザーで入力の準備ができています。"),
	TJS_W("CPUのチェック失敗"),
	TJS_W("CPU check failure: CPU family 4 or lesser is not supported\r\n%1"),
	TJS_W("(info) CPU #%1 : "),
	TJS_W("CPUチェック失敗: サポートしていないCPU\r\n%1"),
	TJS_W("(info) finally detected CPU features : %1"),
	TJS_W("CPU check failure: Not supported CPU\r\n%1"),
	TJS_W("(info) CPU clock : %.1fMHz"),
	TJS_W("Layer bitmap: Buffer underrun detected. Check your drawing code!"),
	TJS_W("Layer bitmap: Buffer overrun detected. Check your drawing code!"),
	TJS_W("Direct3D9 生成失敗"),
	TJS_W("Faild to decide backbuffer format."),
	TJS_W("Faild to create Direct3D9 Device."),
	TJS_W("Faild to set viewport."),
	TJS_W("Faild to set render state."),
	TJS_W("warning : Image size too large. May be cannot create texture."),
	TJS_W("2の累乗サイズのサーフェイスを使用します。"),
	TJS_W("Cannot allocate D3D off-screen surface/HR=%1"),
	TJS_W("BasicDrawDevice: Failed to create Direct3D devices: %1"),
	TJS_W("BasicDrawDevice: Failed to create Direct3D devices: unknown reason"),
	TJS_W("BasicDrawDevice: テクスチャーは既にロックされています (EndBitmapCompletion() を呼ばずに StartBitmapCompletion() を2回呼び出しています), アンロックしてください."),
	TJS_W("Internal error/HR=%1"),
	TJS_W("BasicDrawDevice: (inf) ポリゴン描画に失敗しました/HR=%1"),
	TJS_W("BasicDrawDevice: (inf) IDirect3DDevice::Present failed/HR=%1"),
	TJS_W("ChangeDisplaySettings failed: DISP_CHANGE_RESTART"),
	TJS_W("ChangeDisplaySettings failed: DISP_CHANGE_BADFLAGS"),
	TJS_W("ChangeDisplaySettings failed: DISP_CHANGE_BADPARAM"),
	TJS_W("ChangeDisplaySettings failed: DISP_CHANGE_FAILED"),
	TJS_W("ChangeDisplaySettings failed: DISP_CHANGE_BADMODE"),
	TJS_W("ChangeDisplaySettings failed: DISP_CHANGE_NOTUPDATED"),
	TJS_W("ChangeDisplaySettings 失敗: 不明な理由 (%1)"),
	TJS_W("スクリーンデバイスコンテキストの取得に失敗しました"),
	TJS_W("オフスクリーンビットマップの生成に失敗しました"),
	TJS_W("オフスクリーンデバイスコンテキストの生成に失敗しました"),
	TJS_W("(info) Susie プラグイン情報 : %1"),
	TJS_W("サポートしていない Bitmap ヘッダーが Susie プラグインから渡されました"),
	TJS_W("BasicDrawDevice: Direct3D Device の生成に失敗しました : %1"),
	TJS_W("BasicDrawDevice: Direct3D Device の生成に失敗しました : 不明な理由"),
	TJS_W("Fatal: どの drawer オブジェクトも生成できませんでした"),
	TJS_W("""Basic Draw"" デバイスでは２つ以上のLayer Managerを登録できない"),
	TJS_W("無効なビデオサイズ"),
	TJS_W("API から取得したリフレッシュレート : "),
	TJS_W("リフレッシュレートはまだ間違っているようなので、デフォルト値(16)と仮定します"),
	TJS_W("(info) IDirect3D9 以上のインターフェイスが見つかりました。現在の Direct3D ドライバ情報を取得します..."),
	TJS_W("(info) 失敗"),
	TJS_W("(info) Direct3D 読込み..."),
	TJS_W("d3d9.dll をロードできません"),
	TJS_W("Direct3DCreate9 が d3d9.dll に見つかりません"),
	TJS_W("(info) environment: %1 を使用"),
	TJS_W("(info) 最適なフルスクリーン解像度を検索 ..."),
	TJS_W("(info) condition: 推奨スクリーンモード: %1"),
	TJS_W("(info) condition: モード: %1"),
	TJS_W("(info) condition: ズームモード: %1"),
	TJS_W("(info) environment: デフォルトスクリーンモード: %1"),
	TJS_W("(info) environment: デフォルトスクリーンアスペクトレート: %1 : %2"),
	TJS_W("(info) environment: 有効なディスプレイモード:"),
	TJS_W("(info) Panic! ドライバーから提供されたスクリーンモードに適切なものはありません。デフォルト画面サイズ、色数を試します"),
	TJS_W("(info) result: candidates:"),
	TJS_W("(info) スクリーンモードの %1 を試みる"),
	TJS_W("全スクリーンモードを試しましたが、使用可能なモードはありませんでした"),
	TJS_W("(info) スクリーンモード変更に成功しました"),
	TJS_W("XP3ファイルかフォルダを選択してください"),
	TJS_W("D3D : デバイスは消失しています。現在リセットできません。"),
	TJS_W("D3D : ドライバ内部でエラーが発生しました。アプリケーションをシャットダウンする必要があります。"),
	TJS_W("D3D : メソッドの呼び出しが無効です。メソッドのパラメータが有効なポインタではない等の可能性があります。"),
	TJS_W("D3D : Direct3D が処理を行うのに十分なディスプレイ メモリがありません"),
	TJS_W("D3D : Direct3D が呼び出しを完了するための十分なメモリを割り当てることができませんでした"),
	TJS_W("D3D : テクスチャ サーフェイスのピクセル フォーマットが無効です"),
	TJS_W("D3D : 色値に対して指定されているテクスチャ ブレンディング処理を、デバイスがサポートしていません"),
	TJS_W("D3D : 色値に対して指定されているテクスチャ ブレンディング引数を、デバイスがサポートしていません"),
	TJS_W("D3D : アルファ チャンネルに対して指定されているテクスチャ ブレンディング処理を、デバイスがサポートしていません"),
	TJS_W("D3D : アルファ チャンネルに対して指定されているテクスチャ ブレンディング引数を、デバイスがサポートしていません"),
	TJS_W("D3D : デバイスがサポートしている数より多くのテクスチャ フィルタリング処理を、アプリケーションが要求しています"),
	TJS_W("D3D : 現在のテクスチャ フィルタは同時には使えません"),
	TJS_W("D3D : デバイスが指定されたテクスチャ係数値をサポートしていません"),
	TJS_W("D3D : 現在設定されているレンダリング ステートは同時には使えません"),
	TJS_W("D3D : デバイスが指定されたテクスチャ フィルタをサポートしていません"),
	TJS_W("D3D : 現在のテクスチャは同時には使えません"),
	TJS_W("D3D : 要求された項目が見つかりませんでした"),
	TJS_W("D3D : 指定されたバッファ サイズに保持できる以上のデータが存在します"),
	TJS_W("D3D : デバイスは、消失していますが、現在リセットできます"),
	TJS_W("D3D : このデバイスは、照会されたテクニックをサポートしていません"),
	TJS_W("D3D : 要求されたデバイスの種類が無効です"),
	TJS_W("D3D : 使用されません"),
	TJS_W("D3D : このサーフェスとの間で情報を転送している以前のビット演算が不完全です"),
	TJS_W("D3D : このコードを返したデバイスが原因で、ハードウェア アダプターが OS によってリセットされました"),
	TJS_W("D3D : 指定されたサイズまたはディスプレイ モードのオーバーレイをデバイスがサポートしていません。"),
	TJS_W("D3D : 指定されたサーフェス フォーマットのオーバーレイをデバイスがサポートしていません。"),
	TJS_W("D3D : D3DERR_CANNOTPROTECTCONTENT"),
	TJS_W("D3D : 指定された暗号化アルゴリズムをサポートしていません。"),
	TJS_W("D3D : D3DERR_PRESENT_STATISTICS_DISJOINT"),
	TJS_W("D3D : ハードウェア アダプターが削除されています"),
	TJS_W("D3D : 成功しましたが、このフォーマットに対するミップマップの自動生成はサポートされていません"),
	TJS_W("D3D : Direct3D サブシステム内で原因不明のエラーが発生しました"),
	TJS_W("D3D : 無効なパラメータが関数に渡されました"),
	TJS_W("D3D : 不明なエラーが発生しました"),
	TJS_W("Access Violation: スレッドが適切なアクセス権を持たない仮想アドレスに対して、読み取りまたは書き込みを試みました。"),
	TJS_W("Break Point: ブレークポイントに到達しました。"),
	TJS_W("Data Type Misalignment: 境界整列をサポートしないハードウェア上で、スレッドが境界に整列していないデータの読み取りまたは書き込みを試みました。たとえば、16 ビットの値は 2 バイトの境界線上に、32 ビットの値は 4 バイトの境界線上に整列していなければなりません。"),
	TJS_W("Single Step: トレーストラップなどの単一命令メカニズムから 1 つの命令の実行が通知されました。"),
	TJS_W("Array Bounds Exceede: スレッドが範囲外の配列要素にアクセスしようとしました。使用中のハードウェアは境界チェックをサポートしています。"),
	TJS_W("Denormal Operand: 浮動小数点演算のオペランドの 1 つが不正規化値です。不正規化値とは、小さすぎて標準の浮動小数点値として表現できない値です。"),
	TJS_W("Divide By Zero: スレッドが浮動小数点値を 0 の浮動小数点除数で除算しようとしました。"),
	TJS_W("Inexact Result: 浮動小数点演算の結果を 10 進小数で正確に表現できません。"),
	TJS_W("Invalid Operation: このリストに含まれていない例外が発生しました。"),
	TJS_W("Overflow: 浮動小数点演算の指数が大きく、対応する型によって表現できません。"),
	TJS_W("Stack Check: 浮動小数点演算の結果、スタックのオーバーフローまたはアンダーフローが発生しました。"),
	TJS_W("Underflow: 浮動小数点演算の指数が小さく、対応する型によって表現できません。"),
	TJS_W("Divide By Zero: スレッドが整数値を 0 の整数除数で除算しようとしました。"),
	TJS_W("Overflow: 整数演算結果の最上位ビットが繰り上がりました。"),
	TJS_W("Priv Instruction: 現在のマシンモードで許可されていない演算を行う命令をスレッドが実行しようとしました。"),
	TJS_W("Noncontinuable Exception: 継続不可能な例外が発生した後、スレッドが実行を継続しようとしました。"),
	TJS_W("Guard Page: PAGE_GUARD で保護されたメモリにアクセスしました。"),
	TJS_W("Illegal Instruction: 無効な命令を実行しようとしました。"),
	TJS_W("In Page Error: 存在しないページへアクセスしようとしました、またシステムはページをロードできません。 "),
	TJS_W("Invalid Disposition: 例外ハンドラは無効な配置をディスパッチャに返しました。C言語のような高水準言語では発生しません。"),
	TJS_W("Invalid Handle: 無効な(おそらく既に閉じられている)カーネルオブジェクトのハンドルを使用しました。"),
	TJS_W("Stack Overflow: スタックを使い果たしました。"),
	TJS_W("Unwind Consolidate: フレーム結合が実行されました。"),
	TJS_W("既に表示、もしくは無効になっているウィンドウをモーダル表示することは出来ません。"),
	TJS_W("ウィンドウが1個の時モーダル表示することは出来ません。"),
};
