"\n"
"-- dtoa library ---\n"
"\n"
"The author of this software is David M. Gay.\n"
"\n"
"Copyright (c) 1991, 2000, 2001 by Lucent Technologies.\n"
"\n"
"Permission to use, copy, modify, and distribute this software for any\n"
"purpose without fee is hereby granted, provided that this entire\n"
"notice is included in all copies of any software which is or includes\n"
"a copy or modification of this software and in all copies of the\n"
"supporting documentation for such software.\n"
"\n"
"THIS SOFTWARE IS BEING PROVIDED \"AS IS\", WITHOUT ANY EXPRESS OR\n"
"IMPLIED WARRANTY.  IN PARTICULAR, NEITHER THE AUTHOR NOR LUCENT MAKES\n"
"ANY REPRESENTATION OR WARRANTY OF ANY KIND CONCERNING THE\n"
"MERCHANTABILITY OF THIS SOFTWARE OR ITS FITNESS FOR ANY PARTICULAR\n"
"PURPOSE.\n"
"\n"
"-- Strongtalk assembler --\n"
"\n"
"Copyright (c) 1994-2006 Sun Microsystems Inc.\n"
"All Rights Reserved.\n"
"\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions are\n"
"met:\n"
"\n"
"- Redistributions of source code must retain the above copyright notice,\n"
"this list of conditions and the following disclaimer.\n"
"\n"
"- Redistribution in binary form must reproduce the above copyright\n"
"notice, this list of conditions and the following disclaimer in the\n"
"documentation and/or other materials provided with the distribution.\n"
"\n"
"- Neither the name of Sun Microsystems or the names of contributors may\n"
"be used to endorse or promote products derived from this software without\n"
"specific prior written permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS\n"
"IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,\n"
"THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR\n"
"PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR\n"
"CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\n"
"EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,\n"
"PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\n"
"PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\n"
"LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\n"
"NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
"\n"
"The original source code covered by the above license above has been\n"
"modified significantly by Google Inc.\n"
"Copyright 2006-2008 the V8 project authors. All rights reserved.\n"
"\n"
"-- Valgrind API Header--\n"
"\n"
"This file is part of Valgrind, a dynamic binary instrumentation\n"
"framework.\n"
"\n"
"Copyright (C) 2000-2007 Julian Seward.  All rights reserved.\n"
"\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions\n"
"are met:\n"
"\n"
"1. Redistributions of source code must retain the above copyright\n"
"notice, this list of conditions and the following disclaimer.\n"
"\n"
"2. The origin of this software must not be misrepresented; you must \n"
"not claim that you wrote the original software.  If you use this \n"
"software in a product, an acknowledgment in the product \n"
"documentation would be appreciated but is not required.\n"
"\n"
"3. Altered source versions must be plainly marked as such, and must\n"
"not be misrepresented as being the original software.\n"
"\n"
"4. The name of the author may not be used to endorse or promote \n"
"products derived from this software without specific prior written \n"
"permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE AUTHOR \"AS IS\" AND ANY EXPRESS\n"
"OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\n"
"WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\n"
"ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY\n"
"DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\n"
"DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE\n"
"GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS\n"
"INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,\n"
"WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\n"
"NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
"\n"
"-- V8 Javascript Engine --\n"
"\n"
"Copyright 2006-2009, Google Inc. All rights reserved.\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions are\n"
"met:\n"
"\n"
"* Redistributions of source code must retain the above copyright\n"
"notice, this list of conditions and the following disclaimer.\n"
"* Redistributions in binary form must reproduce the above\n"
"copyright notice, this list of conditions and the following\n"
"disclaimer in the documentation and/or other materials provided\n"
"with the distribution.\n"
"* Neither the name of Google Inc. nor the names of its\n"
"contributors may be used to endorse or promote products derived\n"
"from this software without specific prior written permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
"\"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
"A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\n"
"OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
"SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n"
"LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n"
"DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n"
"THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
"(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
