Krkr2CompatUtils.require("padcommon");

class        Pad extends DebugPadCompatDialog{
	function Pad { super.DebugPadCompatDialog(); }
	function finalize { super.finalize(...); }
	var _title = "Pad";
	var _execEnabled = false;
}
class        DebugScriptEditorCompatPad extends DebugPadCompatDialog{
	function DebugScriptEditorCompatPad { super.DebugPadCompatDialog(); }
	function finalize { super.finalize(...); }
	var _title = "ScriptEditor";
}
